In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):

   def __init__(self, num_features):

    super().__init__()
    # self.linear1 = nn.Linear(num_features, 3)
    # self.relu = nn.ReLU()
    # self.linear2 = nn.Linear(3, 1)
    # self.sigmoid = nn.Sigmoid()
    self.network = nn.Sequential(                                                     #Using Sequential Container
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


   def forward(self, features):
    # out = self.linear1(features)
    # out = self.relu(out)
    # out = self.linear2(out)
    # out = self.sigmoid(out)
    out = self.network(features)

    return out

In [ ]:
# Create Dataset
features = torch.rand(10, 5)
# Create Model
model = Model(features.shape[1])
# Call model for Forward Pass
model(features)

tensor([[0.4388],
        [0.4378],
        [0.4376],
        [0.4371],
        [0.4376],
        [0.4383],
        [0.4399],
        [0.4385],
        [0.4387],
        [0.4392]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.2200, -0.0199,  0.2442,  0.2752, -0.4381],
        [-0.2432,  0.2305,  0.2383, -0.2966, -0.0073],
        [ 0.1812,  0.4389,  0.1509,  0.3797,  0.0374]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.0658,  0.1715, -0.4435]], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### **6 params means 5 weights and 1 bias**