In [51]:
import torch
print(torch.__version__)

2.10.0+cu128


In [52]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
  print("GPU not available. Using CPU.")

GPU is available
Using GPU: Tesla T4


### **Creating Tensors**

In [53]:
# Using empty
torch.empty(2,3)

tensor([[1.6330e-38, 0.0000e+00, 2.5083e-43],
        [4.6243e-44, 2.5083e-43, 4.7644e-44]])

In [54]:
# Using zeroes
p = torch.zeros(3,2)
print(p)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [55]:
# Check type
print(p.dtype)

torch.float32


In [56]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [57]:
# Using rand
torch.rand(2,3)                                           # rand will give float values 0 to 1

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

In [58]:
# Use of seed
b = torch.rand(2,3)                                          # got different values than above

In [59]:
# Use of manual_seed
torch.manual_seed(100)                                      #It ensure that the "random" numbers generated are exactly the same every time the code is executed.
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [60]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
# Other ways

# Using arange
print("Using arange:", torch.arange(2, 9, 2))

Using arange: tensor([2, 4, 6, 8])


In [62]:
# Using linspace[Linearly Spaced]
print("Using linspace:", torch.linspace(0,10,10))

Using linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [63]:
# Using eye [Identity:- 2X2 mptrix]
print("Using eye:", torch.eye(4))

Using eye: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [64]:
# Using full
print("Using full:", torch.full((3,3), 5))

Using full: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [69]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [70]:
x.shape

torch.Size([2, 3])

In [71]:
x.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [72]:
torch.empty_like(x)                                                                           # Creating tensor of same shape ps x

tensor([[ 1082227451502788727,                   81,           1057740240],
        [          1060010064,     1952840038744605, -7486794511346556387]])

In [73]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [74]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [75]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

### **Tensor Data Types**

In [76]:
# Finding data type
x.dtype

torch.int64

In [78]:
# assigning data type
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

tensor([1., 2., 3.])

In [79]:
# Using to()
x.to(torch.float32)                                                                         #will convert existing dtype to other dtype

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### **Mathematical Operations**

#### **1. Scalar Operation**

In [80]:
x = torch.rand(3,3)
x

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [81]:
# addition
x + 1

tensor([[1.1180, 1.1217, 1.7356],
        [1.7118, 1.7876, 1.4183],
        [1.9014, 1.9969, 1.7565]])

In [82]:
# Substraction
x - 1

tensor([[-0.8820, -0.8783, -0.2644],
        [-0.2882, -0.2124, -0.5817],
        [-0.0986, -0.0031, -0.2435]])

In [83]:
# Multiplication
x * 2

tensor([[0.2361, 0.2434, 1.4712],
        [1.4235, 1.5752, 0.8366],
        [1.8028, 1.9938, 1.5130]])

In [84]:
# Division
x / 2

tensor([[0.0590, 0.0608, 0.3678],
        [0.3559, 0.3938, 0.2092],
        [0.4507, 0.4984, 0.3783]])

In [85]:
# Int Division
(x*100)//2

tensor([[ 5.,  6., 36.],
        [35., 39., 20.],
        [45., 49., 37.]])

In [86]:
# Mod
x % 2

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [87]:
# Power
x ** 2

tensor([[0.0139, 0.0148, 0.5411],
        [0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

#### **2. Element wise Operation**

In [88]:
p = torch.rand(2,3)
q = torch.rand(2,3)
print(p)
print(q)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [89]:
## add
p + q
# sub
p - q
# multiply
p * q
# division
p / q
# power
p ** q
# mod
p % q

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [91]:
r = torch.tensor([1,-2,3,-4])

In [92]:
# abs
torch.abs(r)

tensor([1, 2, 3, 4])

In [93]:
# negative
torch.neg(r)

tensor([-1,  2, -3,  4])

In [95]:
s = torch.tensor([1.0, 2.2, 3.5, 4.4])

In [96]:
# round
torch.round(s)

tensor([1., 2., 4., 4.])

In [97]:
# ceil
torch.ceil(s)

tensor([1., 3., 4., 5.])

In [98]:
# floor
torch.floor(s)

tensor([1., 2., 3., 4.])

In [101]:
# clamp
torch.clamp(s, min=2, max=3)

tensor([2.0000, 2.2000, 3.0000, 3.0000])

#### **3. Reduction Operation**

In [106]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [107]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([23., 21.])

In [108]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([6., 7., 9.])

In [109]:
# median
torch.median(e)

tensor(7.)

In [110]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [111]:
# product
torch.prod(e)

tensor(127575.)

In [112]:
# standard deviation
torch.std(e)

tensor(1.9664)

In [113]:
# variance
torch.var(e)

tensor(3.8667)

In [114]:
# argmax
torch.argmax(e)

tensor(1)

In [115]:
# argmin
torch.argmin(e)

tensor(0)

#### **4. Matrix Operations**

In [116]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 9, 7],
        [9, 2, 6]])
tensor([[7, 7],
        [8, 3],
        [6, 1]])


In [117]:
# Matrix Multiplication
torch.matmul(f, g)

tensor([[170,  90],
        [115,  75]])

In [118]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

#Dot product
torch.dot(vector1, vector2)

tensor(11)

In [119]:
# Transpose
torch.transpose(f, 0, 1)

tensor([[8, 9],
        [9, 2],
        [7, 6]])

In [120]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 5., 0.],
        [4., 3., 8.],
        [8., 3., 3.]])

In [121]:
# Determinent
torch.det(h)

tensor(185.)

In [122]:
# Inverse
torch.inverse(h)

tensor([[-0.0811, -0.0811,  0.2162],
        [ 0.2811,  0.0811, -0.2162],
        [-0.0649,  0.1351, -0.0270]])

#### **5. Comparison Operations**

In [123]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 6],
        [4, 0, 8]])
tensor([[4, 7, 2],
        [3, 8, 5]])


In [124]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False,  True, False],
        [False,  True, False]])

#### **6. Special Functions**

In [125]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[6., 2., 9.],
        [5., 0., 4.]])

In [126]:
# Log
torch.log(k)

tensor([[1.7918, 0.6931, 2.1972],
        [1.6094,   -inf, 1.3863]])

In [127]:
# Exponents
torch.exp(k)

tensor([[4.0343e+02, 7.3891e+00, 8.1031e+03],
        [1.4841e+02, 1.0000e+00, 5.4598e+01]])

In [128]:
# Square Root
torch.sqrt(k)

tensor([[2.4495, 1.4142, 3.0000],
        [2.2361, 0.0000, 2.0000]])

In [129]:
# Sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.8808, 0.9999],
        [0.9933, 0.5000, 0.9820]])

ReLU and Softmax are two of the most popular activation functions. ReLU is used in the hidden layers to help the network learn complex patterns, while Softmax is used at the very end (output layer) to turn raw numbers into probabilities for classification.

In [130]:
# Softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.8808, 0.9933],
        [0.2689, 0.1192, 0.0067]])

In [131]:
# Relu
torch.relu(k)

tensor([[6., 2., 9.],
        [5., 0., 4.]])

### **Inplace Operations**

In [132]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])
tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])


In [133]:
m.add_(n)

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [134]:
m

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [135]:
n

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [136]:
torch.relu(m)

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [137]:
m.relu_()

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [138]:
m

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

### **Copying a Tensor**

In [139]:
a = torch.rand(2,3)
a

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [140]:
# Copying tensor 'a' here to 'b'
b = a

In [141]:
b

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [142]:
a[0][0] = 0

In [143]:
a

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [144]:
b          # here b also affects if there's any change in 'a'

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [145]:
id(a)

132261994456128

In [146]:
id(b)

132261994456128

In [147]:
# Copying 'a' using clone()
b = a.clone()

In [148]:
a

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [149]:
b

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [150]:
a[0][0] = 10

In [151]:
a

tensor([[10.0000,  0.6017,  0.4234],
        [ 0.5224,  0.4175,  0.0340]])

In [152]:
b

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [153]:
id(a)

132261994456128

In [154]:
id(b)

132261998443440