In [16]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [18]:
df.shape

(569, 33)

In [19]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [20]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


### **train test split**

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### **Scaling**

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train

array([[ 1.06236762e+00,  1.22571454e+00,  9.44056269e-01, ...,
        -1.61047437e-03, -6.59012273e-01, -2.39055932e-01],
       [ 5.61459984e-01, -1.03486352e+00,  5.00808621e-01, ...,
        -1.21601564e-02, -2.11574017e-01, -7.48833162e-01],
       [ 4.52323684e-01, -1.03187841e-02,  6.14670403e-01, ...,
         1.50397986e+00,  2.18401694e+00,  1.15084951e+00],
       ...,
       [-1.22893501e+00, -3.38175165e-02, -1.22216412e+00, ...,
        -1.02206614e+00,  4.71014273e-01, -2.05833270e-01],
       [-3.48009185e-01, -1.44374146e+00, -4.10492277e-01, ...,
        -9.04964673e-01, -9.77444609e-01, -8.01662640e-01],
       [ 1.78434622e+00,  2.00822234e+00,  1.72482277e+00, ...,
         6.41920127e-01, -7.68422358e-01, -3.20950899e-02]])

In [24]:
y_train

,diagnosis
274,M
406,B
351,M
177,M
229,M
...,...
48,B
488,B
424,B
287,B


### **Lable Encoding**

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [26]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,

##3 **Numpy Arrays to PyTorch Tensors**

In [28]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [29]:
X_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

In [31]:
from torch.utils.data import Dataset, DataLoader

In [32]:
class CustomDataset(Dataset):
  def __init__(self, features, lables):
    self.features = features
    self.lables = lables

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.lables[idx]

In [33]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [35]:
train_dataset[1]

(tensor([ 0.5615, -1.0349,  0.5008,  0.3989, -0.0886, -0.3521, -0.4155, -0.0887,
         -0.2967, -0.5522, -0.6031, -1.0284, -0.5614, -0.4023, -1.0872, -0.7065,
         -0.4280, -0.4745, -0.6855, -0.8024,  0.2919, -0.9965,  0.2540,  0.1112,
         -0.5233, -0.5049, -0.1893, -0.0122, -0.2116, -0.7488]),
 tensor(0.))

In [36]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

### **Defining Model**

In [37]:
import torch.nn as nn                                                                     # Using NN Module

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

### **Important Parameters**

In [38]:
learning_rate = 0.1
epochs = 25

In [39]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define Loss Function
loss_function = nn.BCELoss()


### **Training Pipeline**

In [40]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_lables in train_loader:

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.9913339614868164
Epoch: 1, Loss: 0.6761871576309204
Epoch: 1, Loss: 0.5165250301361084
Epoch: 1, Loss: 0.43126803636550903
Epoch: 1, Loss: 0.37805917859077454
Epoch: 1, Loss: 0.3412245512008667
Epoch: 1, Loss: 0.3139331042766571
Epoch: 1, Loss: 0.29272255301475525
Epoch: 1, Loss: 0.2756442129611969
Epoch: 1, Loss: 0.26151415705680847
Epoch: 1, Loss: 0.24957025051116943
Epoch: 1, Loss: 0.2392987161874771
Epoch: 1, Loss: 0.23033969104290009
Epoch: 1, Loss: 0.22243335843086243
Epoch: 1, Loss: 0.21538686752319336
Epoch: 2, Loss: 0.2090538740158081
Epoch: 2, Loss: 0.20332103967666626
Epoch: 2, Loss: 0.19809909164905548
Epoch: 2, Loss: 0.1933164894580841
Epoch: 2, Loss: 0.18891529738903046
Epoch: 2, Loss: 0.18484781682491302
Epoch: 2, Loss: 0.18107450008392334
Epoch: 2, Loss: 0.17756211757659912
Epoch: 2, Loss: 0.174282506108284
Epoch: 2, Loss: 0.1712116301059723
Epoch: 2, Loss: 0.1683288961648941
Epoch: 2, Loss: 0.16561633348464966
Epoch: 2, Loss: 0.16305837035179138
Epoch

### **Evaluation**

In [41]:
# model evaluation using test_loader
model.eval()                              #Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_lables in test_loader:
    #Forward Pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.9).float()                     #Convert probabilities to binary predictions
    #Calculate accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_lables).float().mean()
    accuracy_list.append(batch_accuracy)

#Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9453
